//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用sushi自动调轴.
        /// </summary>
        public static string 使用sushi自动调轴 {
            get {
                return ResourceManager.GetString("使用sushi自动调轴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原视频文件名.
        /// </summary>
        public static string 原视频文件名 {
            get {
                return ResourceManager.GetString("原视频文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制字幕到视频目录.
        /// </summary>
        public static string 复制字幕到视频目录 {
            get {
                return ResourceManager.GetString("复制字幕到视频目录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字幕文件名.
        /// </summary>
        public static string 字幕文件名 {
            get {
                return ResourceManager.GetString("字幕文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行重命名.
        /// </summary>
        public static string 执行重命名 {
            get {
                return ResourceManager.GetString("执行重命名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最终文件名.
        /// </summary>
        public static string 最终文件名 {
            get {
                return ResourceManager.GetString("最终文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理.
        /// </summary>
        public static string 正在处理 {
            get {
                return ResourceManager.GetString("正在处理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空列表.
        /// </summary>
        public static string 清空列表 {
            get {
                return ResourceManager.GetString("清空列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义字幕扩展名.
        /// </summary>
        public static string 自定义字幕扩展名 {
            get {
                return ResourceManager.GetString("自定义字幕扩展名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频文件名.
        /// </summary>
        public static string 视频文件名 {
            get {
                return ResourceManager.GetString("视频文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择原视频.
        /// </summary>
        public static string 选择原视频 {
            get {
                return ResourceManager.GetString("选择原视频", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择字幕.
        /// </summary>
        public static string 选择字幕 {
            get {
                return ResourceManager.GetString("选择字幕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择视频.
        /// </summary>
        public static string 选择视频 {
            get {
                return ResourceManager.GetString("选择视频", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名完成.
        /// </summary>
        public static string 重命名完成 {
            get {
                return ResourceManager.GetString("重命名完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名成功.
        /// </summary>
        public static string 重命名成功 {
            get {
                return ResourceManager.GetString("重命名成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
    }
}
